-- PUBLISHER
CREATE TABLE PUBLISHER (
    Publisher_ID INT PRIMARY KEY AUTO_INCREMENT,
    Pub_Name VARCHAR(100) NOT NULL,
    Pub_Email VARCHAR(100) NOT NULL,
    Pub_Country VARCHAR(50) NOT NULL
) ENGINE = InnoDB;

-- AUTHOR
CREATE TABLE AUTHOR (
    Author_ID INT PRIMARY KEY AUTO_INCREMENT,
    First_Name VARCHAR(100) NOT NULL,
    Surname VARCHAR(100) NOT NULL,
    Country_Origin VARCHAR(100) NOT NULL
) ENGINE = InnoDB;

-- BOOK
CREATE TABLE BOOK (
    ISBN VARCHAR(13) PRIMARY KEY,
    Title VARCHAR(200) NOT NULL,
    Price DECIMAL(10,2) NOT NULL,
    Quantity_on_Hand INT DEFAULT 0,
    Reorder_Level INT DEFAULT 5,
    Publisher_ID INT NOT NULL,
    FOREIGN KEY (Publisher_ID) REFERENCES PUBLISHER(Publisher_ID)
) ENGINE = InnoDB;

-- BOOK_AUTHOR 
CREATE TABLE BOOK_AUTHOR (
    ISBN VARCHAR(13) NOT NULL,
    Author_ID INT NOT NULL,
    PRIMARY KEY (ISBN, Author_ID),
    FOREIGN KEY (ISBN) REFERENCES BOOK(ISBN),
    FOREIGN KEY (Author_ID) REFERENCES AUTHOR(Author_ID)
) ENGINE = InnoDB;

-- SALE
CREATE TABLE SALE (
    SaleID INT PRIMARY KEY AUTO_INCREMENT,
    SaleDate DATE NOT NULL
) ENGINE = InnoDB;

-- BOOK_SALE 
CREATE TABLE BOOK_SALE (
    ISBN VARCHAR(13) NOT NULL,
    SaleID INT NOT NULL,
    Quantity INT NOT NULL,
    PRIMARY KEY (ISBN, SaleID),
    FOREIGN KEY (ISBN) REFERENCES BOOK(ISBN),
    FOREIGN KEY (SaleID) REFERENCES SALE(SaleID)
) ENGINE = InnoDB;

-- BOOK_ORDER 
CREATE TABLE BOOK_ORDER (
    OrderNo INT PRIMARY KEY AUTO_INCREMENT,
    OrderDate DATE NOT NULL,
    Received BOOLEAN DEFAULT FALSE
) ENGINE = InnoDB;
