CREATE TABLE PUBLISHER (
    Publisher_ID INT PRIMARY KEY NOT NULL AUTO_INCREMENT,
    Pub_Name VARCHAR(100) NOT NULL,
    Pub_Email VARCHAR(100) NOT NULL,
    Pub_Country VARCHAR(50) NOT NULL
    )ENGINE = InnoDB;
    
    CREATE TABLE SALE(
    SaleId  INT PRIMARY KEY NOT NULL AUTO_INCREMENT,
    SaleDate DATE,
    SaleTotal DECIMAL(10,2)
    
)ENGINE = InnoDB;
    
CREATE TABLE BOOK (
    ISBN             VARCHAR(255)    PRIMARY KEY,
    Title            VARCHAR(200)   NOT NULL,
    Price            DECIMAL(10,2),
    Quantity_on_Hand INT            DEFAULT 0,
    Reorder_Level    INT            DEFAULT 5,
    Publisher_ID     INT NOT NULL,
    FOREIGN KEY (Publisher_ID) REFERENCES PUBLISHER(Publisher_ID)
);


CREATE TABLE BOOK_AUTHOR (
    ISBN      VARCHAR(225) NOT NULL,
    Author_ID INT         NOT NULL,
    PRIMARY KEY (ISBN, Author_ID),
    FOREIGN KEY (ISBN)      REFERENCES BOOK(ISBN),
    FOREIGN KEY (Author_ID) REFERENCES AUTHOR(Author_ID)
);


CREATE TABLE BookOrder (
    OrderNo     INT         PRIMARY KEY AUTO_INCREMENT,
    QuantityOrd INT         NOT NULL,
    Received    BOOLEAN DEFAULT FALSE,
    ISBN        VARCHAR(255) NOT NUll,
    FOREIGN KEY (ISBN) REFERENCES BOOK(ISBN)
)ENGINE = InnoDB;

CREATE TABLE BookSale(
    ISBN     VARCHAR(255) NOT NUll,
    SaleID    INT  NOT NULL,
    PRIMARY KEY(ISBN, SaleID),
    FOREIGN KEY(ISBN) REFERENCES BOOK(ISBN),
    FOREIGN KEY(SaleID) REFERENCES SALE(SaleID)
)ENGINE = InnoDB;  
